export const errorConstants = {
	REQUESTING_INCOME_FAILURE: 		'REQUESTING_INCOME_FAILURE',
	REQUESTING_EXPENSE_FAILURE: 	'REQUESTING_EXPENSE_FAILURE',
	AUTHENTICATED_FAILURE: 				'AUTHENTICATED_FAILURE',
	LOGIN_FAILURE: 								'LOGIN_FAILURE',
	REGISTER_FAILURE: 						'REGISTER_FAILURE',
	CLEAR_ALL_ERRORS: 						'CLEAR_ALL_ERRORS',
	REMOVE_ERROR:									'REMOVE_ERROR'
}