export const expensesConstants = {
	GET_ALL_EXPENSES: 				'GET_ALL_EXPENSES',
	GET_ALL_EXPENSES_IN_MONTH: 		'GET_ALL_EXPENSES_IN_MONTH',
	GET_ALL_EXPENSES_IN_RANGE: 		'GET_ALL_EXPENSES_IN_RANGE',

	UPDATE_EXPENSE: 				'UPDATE_EXPENSE',
	REMOVE_EXPENSE: 				'REMOVE_EXPENSE',
	ADD_EXPENSE: 					'ADD_EXPENSE',

	REQUESTING_EXPENSE: 				'REQUESTING_EXPENSE',
	REQUESTING_EXPENSE_SUCCESS: 		'REQUESTING_EXPENSE_SUCCESS',
	REQUESTING_EXPENSE_FAILURE: 		'REQUESTING_EXPENSE_FAILURE'
}