export const incomesConstants = {
	GET_ALL_INCOMES: 			'GET_ALL_INCOMES',
	GET_ALL_INCOMES_IN_MONTH: 	'GET_ALL_INCOMES_IN_MONTH',
	GET_ALL_INCOMES_IN_RANGE: 	'GET_ALL_INCOMES_IN_RANGE',

	GETTING_INCOME: 			'GETTING_INCOME',
	GETTING_INCOME_SUCCESS: 	'GETTING_INCOME_SUCCESS',
	GETTING_INCOME_FAILURE: 	'GETTING_INCOME_FAILURE',

	UPDATE_INCOME: 				'UPDATE_INCOME',

	UPDATING_INCOME: 			'UPDATING_INCOME',
	UPDATING_INCOME_SUCCESS: 	'UPDATING_INCOME_SUCCESS',
	UPDATING_INCOME_FAILURE: 	'UPDATING_INCOME_FAILURE',

	REMOVE_INCOME: 				'REMOVE_INCOME',

	REMOVING_INCOME: 			'REMOVING_INCOME',
	REMOVING_INCOME_SUCCESS: 	'REMOVING_INCOME_SUCCESS',
	REMOVING_INCOME_FAILURE: 	'REMOVING_INCOME_FAILURE',

	ADD_INCOME: 				'ADD_INCOME',

	ADDING_INCOME: 				'ADDING_INCOME',
	ADDING_INCOME_SUCCESS: 		'ADDING_INCOME_SUCCESS',
	ADDING_INCOME_FAILURE: 		'ADDING_INCOME_FAILURE'
}