export const incomesConstants = {
	GET_ALL_INCOMES: 			'GET_ALL_INCOMES',
	GET_ALL_INCOMES_IN_MONTH: 	'GET_ALL_INCOMES_IN_MONTH',
	GET_ALL_INCOMES_IN_RANGE: 	'GET_ALL_INCOMES_IN_RANGE',

	UPDATE_INCOME: 				'UPDATE_INCOME',
	REMOVE_INCOME: 				'REMOVE_INCOME',
	ADD_INCOME: 				'ADD_INCOME',

	REQUESTING_INCOME: 			'REQUESTING_INCOME',
	REQUESTING_INCOME_SUCCESS: 	'REQUESTING_INCOME_SUCCESS'
}