export const userConstants = {
	REGISTER_REQUEST: 				'REGISTER_REQUEST',
	REGISTER_SUCCESS: 				'REGISTER_SUCCESS',
	REGISTER_FAILURE: 				'REGISTER_FAILURE',
	
	REGISTERING_USER: 				'REGISTERING_USER',

	LOGIN_REQUEST: 					'LOGIN_REQUEST',
	LOGIN_SUCCESS: 					'LOGIN_SUCCESS',
	LOGIN_FAILURE: 					'LOGIN_FAILURE',

	LOGOUT: 						'LOGOUT',

	AUTHENTICATED_SUCCESS: 			'AUTHENTICATED_SUCCESS',
	AUTHENTICATED_FAILURE: 			'AUTHENTICATED_FAILURE'
}