export const userConstants = {
	REGISTER_REQUEST: 				'REGISTER_REQUEST',
	REGISTER_SUCCESS: 				'REGISTER_SUCCESS',
	
	REGISTERING_USER: 				'REGISTERING_USER',

	LOGIN_REQUEST: 					'LOGIN_REQUEST',
	LOGIN_SUCCESS: 					'LOGIN_SUCCESS',

	UPDATING_USER: 					'UPDATING_USER',
	UPDATING_SUCCESS: 			'UPDATING_SUCCESS',

	LOGOUT: 						'LOGOUT',

	AUTHENTICATED_SUCCESS: 			'AUTHENTICATED_SUCCESS'
}